print("my name is Kate")
print("I was born in May")
print("my name is colby")
print("I was born in April")
print("My favorite food is the hearts of men")
print("My favorite dirnk is the tears of men")
